// Generated by gencpp from file custom_msgs/custom.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_CUSTOM_H
#define CUSTOM_MSGS_MESSAGE_CUSTOM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct custom_
{
  typedef custom_<ContainerAllocator> Type;

  custom_()
    : x()
    , y()
    , theta()  {
    }
  custom_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , theta(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _x_type;
  _x_type x;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _y_type;
  _y_type y;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::custom_msgs::custom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::custom_<ContainerAllocator> const> ConstPtr;

}; // struct custom_

typedef ::custom_msgs::custom_<std::allocator<void> > custom;

typedef boost::shared_ptr< ::custom_msgs::custom > customPtr;
typedef boost::shared_ptr< ::custom_msgs::custom const> customConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::custom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::custom_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::custom_<ContainerAllocator1> & lhs, const ::custom_msgs::custom_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::custom_<ContainerAllocator1> & lhs, const ::custom_msgs::custom_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::custom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::custom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::custom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::custom_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::custom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::custom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df8fc9de899ddde5dfec399a5e112d32";
  }

  static const char* value(const ::custom_msgs::custom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf8fc9de899ddde5ULL;
  static const uint64_t static_value2 = 0xdfec399a5e112d32ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/custom";
  }

  static const char* value(const ::custom_msgs::custom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] x\n"
"int32[] y\n"
"int32[] theta\n"
;
  }

  static const char* value(const ::custom_msgs::custom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::custom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct custom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::custom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::custom_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "theta[]" << std::endl;
    for (size_t i = 0; i < v.theta.size(); ++i)
    {
      s << indent << "  theta[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.theta[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_CUSTOM_H
